name: deploy-py-lambda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: kohrongying/py-lambda-action@v1.0.3
      with:
        lambda_layer_arn: 'arn:aws:lambda:eu-west-1:907146102603:layer:irl-schengen-layer'
        lambda_function_name: 'irl-schengen-bot'
        exclude_files: 'README.md'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
